(require 'helm)
(require 'helm-config)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key(kbd "M-y") 'helm-show-kill-ring)
(global-set-key(kbd "C-x b") 'helm-mini)
(helm-mode 1)
(provide 'init-helm)
